// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/beranda": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/products/:slug": {
    params: {
      "slug": string;
    };
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/about": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/nsc-admin-panel-x9k2": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/beranda" | "/products" | "/products/:slug" | "/blog" | "/blog/:slug" | "/about" | "/projects" | "/contact" | "/nsc-admin-panel-x9k2" | "/*";
  };
  "./pages/RedirectToBeranda.jsx": {
    id: "pages/RedirectToBeranda";
    page: "/";
  };
  "./pages/Home.jsx": {
    id: "pages/Home";
    page: "/beranda";
  };
  "./pages/Products.jsx": {
    id: "pages/Products";
    page: "/products";
  };
  "./pages/ProductDetail.jsx": {
    id: "pages/ProductDetail";
    page: "/products/:slug";
  };
  "./pages/Blog.jsx": {
    id: "pages/Blog";
    page: "/blog";
  };
  "./pages/BlogDetail.jsx": {
    id: "pages/BlogDetail";
    page: "/blog/:slug";
  };
  "./pages/About.jsx": {
    id: "pages/About";
    page: "/about";
  };
  "./pages/Projects.jsx": {
    id: "pages/Projects";
    page: "/projects";
  };
  "./pages/Contact.jsx": {
    id: "pages/Contact";
    page: "/contact";
  };
  "./pages/Admin.jsx": {
    id: "pages/Admin";
    page: "/nsc-admin-panel-x9k2";
  };
  "./pages/NotFound.jsx": {
    id: "pages/NotFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "pages/RedirectToBeranda": typeof import("./src/./pages/RedirectToBeranda.jsx");
  "pages/Home": typeof import("./src/./pages/Home.jsx");
  "pages/Products": typeof import("./src/./pages/Products.jsx");
  "pages/ProductDetail": typeof import("./src/./pages/ProductDetail.jsx");
  "pages/Blog": typeof import("./src/./pages/Blog.jsx");
  "pages/BlogDetail": typeof import("./src/./pages/BlogDetail.jsx");
  "pages/About": typeof import("./src/./pages/About.jsx");
  "pages/Projects": typeof import("./src/./pages/Projects.jsx");
  "pages/Contact": typeof import("./src/./pages/Contact.jsx");
  "pages/Admin": typeof import("./src/./pages/Admin.jsx");
  "pages/NotFound": typeof import("./src/./pages/NotFound.jsx");
};